### ISSUE TITLE
Make a `ReceiverInactiveError` exception for receivers turned to peekables

### ISSUE THREAD

**Issue by shsms** [frequenz-floss/frequenz-channels-python#52]
While we are introducing our own exceptions I would also consider adding a specific exception for this (maybe `ReceiverInactiveError`?), `EOFError` is only used by `input()`, so it feels a bit weird to raise this exception here.

_Originally posted by @leandro-lucarella-frequenz in https://github.com/frequenz-floss/frequenz-channels-python/pull/42#discussion_r1021982329_

**Comment by leandro-lucarella-frequenz** [comment]
This makes me ask another question. Do we really need to be able to convert a `Receiver` into a `Peekable` instead of just getting a new `Peekable` from the channel?

If we really need this, can we just create a new `Peekable` instead of converting a `Receiver`? Basically forwarding `Receiver.new_peekable()` to `self._channel.new_peekable()`. The user then can decide if they want to `del receiver` or not.

This seems to make a cleaner and less error prone interface.
